experiment:
  exp_root_path:  /shared/experiments/active_learning/alssl/dn/
  data_path: /shared/projects/active_learning/
  dataset: bloodmnist
  wandb_entitiy: dnogina

strategy:
  strategy_name: RandomStrategy
  strategy_params: {}
  budget_percent: 0.5
  initial_train_percent: 1
  initial_val_size: 1000
  n_iter: 10

coldstart:
  coldstart_name: RandomColdStart
  coldstart_params: {}

training:
  backbone: effnet_b0
  finetune: False
  optuna_trials: 25
  include_param_loss: False
  batch_size: 100
  batch_size_prediction: 1500
  num_epochs: 20
  learning_rate: 0.0001
  random_seed: 1
  num_workers: 12
  check_val_every_n_epoch: 1
  optimizer_kwargs:
    weight_decay: 0.001