experiment:
  exp_root_path: /shared/experiments/active_learning/alssl/entropy
  exp_name: example

strategy:
  strategy_name: ALSSLStrategy
  num_neighbours: 500
  budget_size: 50
  initial_train_size: 5000
  initial_val_size: 200
  n_iter: 10

training:
  batch_size: 50 # 100
  num_epochs: 1
  learning_rate: 0.00001
  random_seed: 0
  num_workers: 16
  checkpoint_every_n_epochs: 1
  check_val_every_n_epoch: 1
  optimizer_kwargs:
    weight_decay: 0.001
  scheduler_kwargs:
    gamma: 0.1
    milestones:
      - 20

dataset_transforms:
  crop_size: 32
  padding: 4
  image_size:
    - 224
    - 224
  antialias: true
  RandomRotation: 10
  normalize_mean:
    - 0.485
    - 0.456
    - 0.4
  normalize_std:
    - 0.229
    - 0.224
    - 0.225