experiment:
  exp_root_path:  /shared/experiments/active_learning/alssl/dn/
  data_path: /shared/projects/active_learning/
  dataset: bloodmnist

strategy:
  strategy_name: EntropyStrategy
  strategy_params: {}
    # num_neighbours: 500
  budget_percent: 5
  initial_train_percent: 5
  initial_val_size: 200
  n_iter: 2

training:
  batch_size: 100
  num_epochs: 2 #50
  learning_rate: 0.00001
  random_seed: 0
  num_workers: 16
  checkpoint_every_n_epochs: 50
  check_val_every_n_epoch: 1
  optimizer_kwargs:
    weight_decay: 0.001
  scheduler_kwargs:
    gamma: 0.1
    milestones:
      - 20